# Test file generated by ChatGPT

import unittest
from unittest.mock import mock_open, patch
from Source.ConfigurationManager import ConfigurationManager

class TestConfigurationManager(unittest.TestCase):
    def setUp(self):
        # Reflecting the example config content you provided
        self.mock_config_data = "file_extensions=.cpp,.hpp"

    def test_get_config_file_extensions(self):
        # Setup a mock open function that reads our mock config data
        mock_file_open = mock_open(read_data=self.mock_config_data)
        with patch('builtins.open', mock_file_open):
            # Initialize ConfigurationManager with the mocked file data
            config_manager = ConfigurationManager('dummy_config_file')
            file_extensions = config_manager.getConfigFileExtensions()

        # Check if the getConfigFileExtensions method returns the correct list
        self.assertEqual(file_extensions, ['.cpp', '.hpp'])

if __name__ == '__main__':
    unittest.main()