# Test file generated by ChatGPT

import unittest
from unittest.mock import mock_open, patch
from Source.ConfigurationManager import ConfigurationManager

class TestConfigurationManager(unittest.TestCase):
    def setUp(self):
        # Reflecting the example config content you provided
        self.mock_config_data = None

    def test_CppAndHpp(self):
        # Setup a mock open function that reads our mock config data

        self.mock_config_data = "file_extensions=.cpp,.hpp"

        mock_file_open = mock_open(read_data=self.mock_config_data)
        with patch('builtins.open', mock_file_open):
            # Initialize ConfigurationManager with the mocked file data
            config_manager = ConfigurationManager('dummy_config_file')
            file_extensions = config_manager.getConfigFileExtensions()

        # Check if the getConfigFileExtensions method returns the correct list
        self.assertEqual(file_extensions, ['.cpp', '.hpp'])


    def test_MissingOneArg(self):
        # Setup a mock open function that reads our mock config data

        self.mock_config_data = "file_extensions=.cpp,.hpp"

        mock_file_open = mock_open(read_data=self.mock_config_data)
        with patch('builtins.open', mock_file_open):
            # Initialize ConfigurationManager with the mocked file data
            config_manager = ConfigurationManager('dummy_config_file')
            file_extensions = config_manager.getConfigFileExtensions()

        # Check if the getConfigFileExtensions method returns the correct list
        self.assertNotEqual(file_extensions, ['.cpp'])


    def test_LotsOfArgs(self):
        # Setup a mock open function that reads our mock config data

        self.mock_config_data = "file_extensions=.cpp,.hpp,.html,.css,.js,.pl,.lua"

        mock_file_open = mock_open(read_data=self.mock_config_data)
        with patch('builtins.open', mock_file_open):
            # Initialize ConfigurationManager with the mocked file data
            config_manager = ConfigurationManager('dummy_config_file')
            file_extensions = config_manager.getConfigFileExtensions()

        # Check if the getConfigFileExtensions method returns the correct list
        self.assertEqual(file_extensions, ['.cpp', '.hpp', '.html', '.css', '.js', '.pl', '.lua'])


    def test_NoArgs(self):
    # Setup a mock open function that reads our mock config data

        self.mock_config_data = "file_extensions="

        mock_file_open = mock_open(read_data=self.mock_config_data)
        with patch('builtins.open', mock_file_open):
            # Initialize ConfigurationManager with the mocked file data
            config_manager = ConfigurationManager('dummy_config_file')
            file_extensions = config_manager.getConfigFileExtensions()

        # Check if the getConfigFileExtensions method returns the correct list
        self.assertEqual(file_extensions, [])

if __name__ == '__main__':
    unittest.main()